### ISSUE TITLE
Table widths are different

### ISSUE THREAD

**Issue by sayanee** [sauvc/2018#13]
![image](https://user-images.githubusercontent.com/413879/29748003-b9f6407a-8b3e-11e7-800a-1291a30a1fd6.png)

**Comment by notthetup** [comment]
It seem to be something related to number of digits in the "Time" column. Having a single 4 digit time (10.30) in the table causes the width to increase.

**Comment by sayanee** [comment]
Need to amend the `width`:
https://github.com/sauvc/sauvc.github.io/blob/master/css/main.css#L338-L348

```css
.table td:nth-child(1) {
  width: 15%;
}

.table td:nth-child(2) {
  width: 55%;
}

.table td:nth-child(3) {
  width: 30%;
}
```
